"""add count_place

Revision ID: 00d6dbd50d82
Revises: d9b0ba172b0f
Create Date: 2026-05-13 18:12:22.068934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d6dbd50d82'
down_revision: Union[str, Sequence[str], None] = 'd9b0ba172b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('halls', sa.Column('count_place', sa.Integer(), nullable=False))
    op.drop_column('halls', 'places')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('places', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('halls', 'count_place')
    op.drop_table('places')
    # ### end Alembic commands ###
