"""change movie age_limit to integer

Revision ID: 0769fd2d0bf2
Revises: 3f4c6abb5fb9
Create Date: 2026-05-16 18:35:39.391890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0769fd2d0bf2'
down_revision: Union[str, Sequence[str], None] = '3f4c6abb5fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
