"""change movie age_limit to integer

Revision ID: 3f4c6abb5fb9
Revises: 434344d61c04
Create Date: 2026-05-16 18:34:05.555313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4c6abb5fb9'
down_revision: Union[str, Sequence[str], None] = '434344d61c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movies', ['name'])
    op.add_column('sessions', sa.Column('number_hall', sa.Integer(), nullable=False))
    op.add_column('sessions', sa.Column('movie_name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('sessions_hall_id_start_time_key'), 'sessions', type_='unique')
    op.create_unique_constraint(None, 'sessions', ['number_hall', 'start_time'])
    op.drop_constraint(op.f('sessions_hall_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_movie_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'movies', ['movie_name'], ['name'])
    op.create_foreign_key(None, 'sessions', 'halls', ['number_hall'], ['number_hall'])
    op.drop_column('sessions', 'hall_id')
    op.drop_column('sessions', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('hall_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_movie_id_fkey'), 'sessions', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('sessions_hall_id_fkey'), 'sessions', 'halls', ['hall_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='unique')
    op.create_unique_constraint(op.f('sessions_hall_id_start_time_key'), 'sessions', ['hall_id', 'start_time'], postgresql_nulls_not_distinct=False)
    op.drop_column('sessions', 'movie_name')
    op.drop_column('sessions', 'number_hall')
    op.drop_constraint(None, 'movies', type_='unique')
    # ### end Alembic commands ###
