"""change movie age_limit to integer

Revision ID: 434344d61c04
Revises: c25063e45b17
Create Date: 2026-05-16 17:17:44.793278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434344d61c04'
down_revision: Union[str, Sequence[str], None] = 'c25063e45b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sessions', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'movie_id')
    # ### end Alembic commands ###
