"""mini up

Revision ID: 6cbb1557d187
Revises: e7ad64693dde
Create Date: 2026-05-13 22:46:18.343012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbb1557d187'
down_revision: Union[str, Sequence[str], None] = 'e7ad64693dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('place_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'place_type')
    # ### end Alembic commands ###
