"""add balance to clients

Revision ID: aebb00771fff
Revises: e3cc614888c9
Create Date: 2026-05-15 19:55:28.031928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebb00771fff'
down_revision: Union[str, Sequence[str], None] = 'e3cc614888c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('number_hall', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'halls', ['number_hall'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'halls', type_='unique')
    op.drop_column('halls', 'number_hall')
    # ### end Alembic commands ###
