"""total upgrade

Revision ID: c25063e45b17
Revises: aebb00771fff
Create Date: 2026-05-16 16:34:01.374515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c25063e45b17'
down_revision: Union[str, Sequence[str], None] = 'aebb00771fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('aboutMovie', sa.Text(), nullable=False),
    sa.Column('age_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hall_id', 'start_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('movies')
    # ### end Alembic commands ###
