"""add count_place

Revision ID: e7ad64693dde
Revises: 00d6dbd50d82
Create Date: 2026-05-13 21:57:53.315765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ad64693dde'
down_revision: Union[str, Sequence[str], None] = '00d6dbd50d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'places', ['hall_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='unique')
    op.drop_column('places', 'number')
    # ### end Alembic commands ###
