"""add balance to clients

Revision ID: 28ab1630f1cc
Revises: e96e661a8bbf
Create Date: 2026-05-15 20:06:25.188844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ab1630f1cc'
down_revision: Union[str, Sequence[str], None] = 'e96e661a8bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('hall_number', sa.Integer(), nullable=False))
    op.drop_column('tickets', 'hall_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('hall_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tickets', 'hall_number')
    # ### end Alembic commands ###
