"""add balance to clients

Revision ID: 9691c03de379
Revises: 28ab1630f1cc
Create Date: 2026-05-15 20:32:44.737009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9691c03de379'
down_revision: Union[str, Sequence[str], None] = '28ab1630f1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'tickets',
        sa.Column('ticket_status', sa.String(), nullable=True, server_default='active')
    )
    op.execute("UPDATE tickets SET ticket_status = 'active' WHERE ticket_status IS NULL")
    op.alter_column('tickets', 'ticket_status', server_default=None, nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ticket_status')
    # ### end Alembic commands ###
