"""init db

Revision ID: bffc19f9486d
Revises: 207bfe7101e5
Create Date: 2026-05-10 16:00:32.457735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffc19f9486d'
down_revision: Union[str, Sequence[str], None] = '207bfe7101e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###
