"""add balance to clients

Revision ID: e96e661a8bbf
Revises: 0b908574a9e9
Create Date: 2026-05-15 18:32:38.745783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96e661a8bbf'
down_revision: Union[str, Sequence[str], None] = '0b908574a9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column(
        'tickets',
        sa.Column('ticket_type', sa.String(), nullable=True, server_default='standard')
    )
    op.execute("UPDATE tickets SET ticket_type = 'standard' WHERE ticket_type IS NULL")
    op.alter_column('tickets', 'ticket_type', server_default=None, nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ticket_type')
    # ### end Alembic commands ###
