"""add ip ticket

Revision ID: eb0547d791ad
Revises: 9691c03de379
Create Date: 2026-05-16 21:16:10.891348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0547d791ad'
down_revision: Union[str, Sequence[str], None] = '9691c03de379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('name_movie', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'start_time')
    op.drop_column('tickets', 'name_movie')
    # ### end Alembic commands ###
